/* OMMS core: icons, data layer, UI helpers, shell */
let VIEW;const OMMS={mount:f=>{VIEW=f}};
const P={dash:'<path d="M3 11l9-8 9 8v10H3z"/>',emp:'<circle cx="9" cy="8" r="4"/><path d="M2 21c0-4 3-6 7-6s7 2 7 6"/>',vac:'<path d="M18 2l4 4M15 5l4 4M7 13l8-8 4 4-8 8zM4 20l3-3"/>',exam:'<path d="M6 3v6a4 4 0 008 0V3M10 13v3a5 5 0 0010 0v-2"/>',co:'<path d="M4 21V4h10v17M14 9h6v12M8 8h2M8 12h2M8 16h2"/>',rep:'<path d="M4 4h12l4 4v12H4zM8 16v-4M12 16V9M16 16v-2"/>',cal:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 3v4M16 3v4"/>',set:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2"/>',bell:'<path d="M6 16V11a6 6 0 0112 0v5l2 2H4zM10 21h4"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/>',shield:'<path d="M12 2l8 3v6c0 5-3.5 9-8 11-4.5-2-8-6-8-11V5z"/><path d="M12 8v6M9 11h6"/>',warn:'<path d="M12 3l10 18H2zM12 10v5M12 18v.5"/>',ok:'<path d="M5 12l5 5 9-10"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2"/>',out:'<path d="M9 4H4v16h5M16 8l4 4-4 4M20 12H9"/>'};
const ic=n=>`<svg class="i" viewBox="0 0 24 24">${P[n]}</svg>`;
/* ---------- Data layer (swap for API calls later) ---------- */
const DB={
 companies:[{n:'Algeria Textiles SARL',ind:'Textile',emp:120,ct:'contact@algtextiles.dz'},{n:'SNC El Manar',ind:'Logistics',emp:85,ct:'contact@elmanar.dz'},{n:'Construction Plus',ind:'Construction',emp:200,ct:'contact@constplus.dz'},{n:'Techno Algeria',ind:'Maintenance',emp:150,ct:'contact@techno.dz'},{n:'Hydraulics DZ',ind:'Industry',emp:90,ct:'contact@hydraulics.dz'}],
 emps:[{id:'EMP-1024',n:'Yasmine Belkacem',co:'Algeria Textiles SARL',dep:'Production',st:'Active',fit:'Fit for work',dob:'1991-06-12',ph:'+213 661 22 41 08',pos:'Machine Operator'},{id:'EMP-0871',n:'Mohamed Zidane',co:'SNC El Manar',dep:'Logistics',st:'Active',fit:'Fit for work',dob:'1995-06-14',ph:'+213 661 23 45 67',pos:'Logistics Coordinator'},{id:'EMP-0632',n:'Lina Khelifi',co:'Construction Plus',dep:'Site Work',st:'Active',fit:'Restricted',dob:'1988-02-03',ph:'+213 550 11 90 21',pos:'Site Supervisor'},{id:'EMP-0417',n:'Rachid Bouzid',co:'Techno Algeria',dep:'Maintenance',st:'Active',fit:'Fit for work',dob:'1984-11-27',ph:'+213 770 38 55 12',pos:'Technician'},{id:'EMP-0389',n:'Amira Daoud',co:'Algeria Textiles SARL',dep:'Production',st:'Active',fit:'Fit for work',dob:'1993-09-08',ph:'+213 655 70 14 33',pos:'Quality Inspector'},{id:'EMP-0276',n:'Samir Haddad',co:'Hydraulics DZ',dep:'Quality',st:'Inactive',fit:'Pending review',dob:'1979-04-19',ph:'+213 540 62 88 90',pos:'QC Engineer'}],
 vacs:[['EMP-1024','Hepatitis B','2026-03-17','2027-03-17','Completed'],['EMP-0871','Influenza','2026-03-20','2026-09-20','Pending'],['EMP-0632','Tetanus','2024-11-15','2026-11-15','Completed'],['EMP-0417','COVID-19','2025-01-08','2026-01-08','Pending'],['EMP-0389','Hepatitis B','2025-04-10','2026-04-10','Pending']],
 exams:[['EMP-1024','General Checkup','2026-03-12','Completed'],['EMP-0871','Vision Test','2026-03-20','Completed'],['EMP-0632','Respiratory','2026-01-15','Pending'],['EMP-0417','Hearing Test','2026-01-09','Completed'],['EMP-0389','Blood Test','2026-04-10','Completed']],
 appts:[['24','Oct','Medical Examination','EMP-0142','09:00'],['24','Oct','Vaccination','EMP-0678','11:30'],['25','Oct','Medical Examination','EMP-0310','14:00'],['26','Oct','Vaccination','EMP-0821','10:00']],
 notes:[['warn','rk','2 employees are overdue for vaccination','Today, 09:15'],['rep','in','Medical report #REP-0042 is ready','Yesterday, 16:32'],['ok','ok','New company registration: Algeria Textiles SARL','Yesterday, 11:20'],['bell','pe','Reminder: 5 employees need medical examination','2 days ago'],['vac','ok','Vaccination completed for Mohamed Zidane','3 days ago']],
 acts:[['vac','ok','New vaccination record','Employee #EMP-1024','2 hours ago'],['ok','in','Medical examination completed','Employee #EMP-0871','4 hours ago'],['co','in','New company registered','Algeria Textiles SARL','6 hours ago'],['bell','pe','Vaccination reminder','Employee #EMP-0632','8 hours ago'],['rep','pe','Report generated','Monthly summary','10 hours ago']]};
try{const s=localStorage.getItem('omms_db');if(s)Object.assign(DB,JSON.parse(s))}catch(e){}
const save=()=>{try{localStorage.setItem('omms_db',JSON.stringify(DB))}catch(e){}};
const S={user:sessionStorage.getItem('omms_user'),tab:'Medical History',q:sessionStorage.getItem('omms_q')||'',filt:''};
const bd=s=>{const m={Active:'ok',Completed:'ok','Fit for work':'ok','Up to date':'ok',Pending:'pe','Due soon':'pe',Restricted:'pe','Pending review':'pe',Inactive:'rk',Overdue:'rk'};return`<span class="bd ${m[s]||'in'}">${s}</span>`};
const tbl=(h,r,clk)=>`<div class="tw"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.map(x=>`<tr ${clk?`class="c" onclick="go('${clk(x)}')"`:''}>${x.cells.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${r.length?'':'<div class="empty">No records found</div>'}`;
const toast=m=>{const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2200)};
const PG={exams:'examinations',calendar:'appointments'};
const go=h=>{const m=h.match(/^\/employee\/(.+)$/);location.href=m?'employee-details.html?id='+encodeURIComponent(m[1]):(PG[h.slice(1)]||h.slice(1))+'.html'};
const nm=id=>(DB.emps.find(e=>e.id===id)||{n:id}).n;
/* ---------- Charts ---------- */
function line(a,b,w=640,h=220){const m=Math.max(...a,...b)*1.1,x=i=>30+i*(w-50)/11,y=v=>h-24-v/m*(h-44);const p=s=>s.map((v,i)=>`${i?'L':'M'}${x(i)},${y(v)}`).join('');
 const mo='JFMAMJJASOND'.split('');return`<svg viewBox="0 0 ${w} ${h}" style="width:100%"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2dd4a7" stop-opacity=".35"/><stop offset="1" stop-color="#2dd4a7" stop-opacity="0"/></linearGradient></defs>${[0,1,2,3].map(i=>`<line x1="30" x2="${w-20}" y1="${20+i*(h-44)/3}" y2="${20+i*(h-44)/3}" stroke="currentColor" opacity=".1"/>`).join('')}<path d="${p(b)}L${x(11)},${h-24}L${x(0)},${h-24}Z" fill="url(#g)"/><path d="${p(a)}" fill="none" stroke="#4f8cff" stroke-width="2.5"/><path d="${p(b)}" fill="none" stroke="#2dd4a7" stroke-width="2.5"/>${mo.map((l,i)=>`<text x="${x(i)}" y="${h-6}" fill="currentColor" opacity=".55" font-size="11" text-anchor="middle">${l}</text>`).join('')}</svg>`}
function donut(p){const r=52,c=2*Math.PI*r;return`<svg viewBox="0 0 140 140" width="140"><circle cx="70" cy="70" r="${r}" fill="none" stroke="var(--line)" stroke-width="14"/><circle cx="70" cy="70" r="${r}" fill="none" stroke="#2dd4a7" stroke-width="14" stroke-dasharray="${c*p/100} ${c}" transform="rotate(-90 70 70)" stroke-linecap="round"/><text x="70" y="70" text-anchor="middle" fill="currentColor" font-size="24" font-weight="700">${p}%</text><text x="70" y="88" text-anchor="middle" fill="currentColor" opacity=".6" font-size="11">Completed</text></svg>`}
/* ---------- Modals ---------- */
function modal(title,fields,done){const d=document.createElement('div');d.className='modal';d.innerHTML=`<div><h2 style="margin-bottom:16px">${title}</h2><div class="fg">${fields.map(f=>`<label class="${f[2]||''}">${f[0]}${f[1]=='sel'?`<select>${f[3].map(o=>`<option>${o}</option>`).join('')}</select>`:`<input type="${f[1]}">`}</label>`).join('')}</div><div class="row" style="justify-content:flex-end;margin-top:20px"><button class="btn o" id="mx">Cancel</button><button class="btn" id="ms">Save</button></div></div>`;document.body.appendChild(d);d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');const esc=e=>{if(e.key=='Escape'){d.remove();removeEventListener('keydown',esc)}};addEventListener('keydown',esc);d.querySelector('input,select').focus();
 d.onclick=e=>{if(e.target===d)d.remove()};d.querySelector('#mx').onclick=()=>d.remove();d.querySelector('#ms').onclick=()=>{done([...d.querySelectorAll('input,select')].map(i=>i.value));save();d.remove();render()}}
const cn=()=>DB.companies.map(c=>c.n),en=()=>DB.emps.map(e=>e.id+' — '+e.n);
const addEmp=()=>modal('Add Employee',[['Full name','text'],['Company','sel','',cn()],['Department','text'],['Position','text'],['Date of birth','date'],['Phone','tel']],v=>{if(!v[0])return toast('Name is required');DB.emps.unshift({id:'EMP-'+(1100+DB.emps.length),n:v[0],co:v[1],dep:v[2]||'—',st:'Active',fit:'Pending review',dob:v[4]||'—',ph:v[5]||'—',pos:v[3]||'—'});toast('Employee added')});
const addVac=()=>modal('Add Vaccination',[['Employee','sel','w',en()],['Vaccine','sel','',['Hepatitis B','Influenza','Tetanus','COVID-19']],['Date','date'],['Next dose','date']],v=>{DB.vacs.unshift([v[0].split(' ')[0],v[1],v[2]||'—',v[3]||'—','Completed']);toast('Vaccination recorded')});
const addExam=()=>modal('Schedule Examination',[['Employee','sel','w',en()],['Type','sel','',['General Checkup','Vision Test','Respiratory','Hearing Test','Blood Test']],['Date','date']],v=>{DB.exams.unshift([v[0].split(' ')[0],v[1],v[2]||'—','Pending']);toast('Examination scheduled')});
const addCo=()=>modal('Add Company',[['Company name','text','w'],['Industry','text'],['Employees','number'],['Contact email','email','w']],v=>{if(!v[0])return toast('Name is required');DB.companies.unshift({n:v[0],ind:v[1]||'—',emp:+v[2]||0,ct:v[3]||'—'});toast('Company added')});
/* ---------- Views ---------- */
const head=(t,s,btns='')=>`<div class="row sp"><div><h1>${t}</h1><p class="sub">${s}</p></div><div class="row">${btns}</div></div>`;
const btn=(t,f,i='plus')=>`<button class="btn" onclick="${f}()">${ic(i)}${t}</button>`;
const empRows=l=>l.map(e=>({id:e.id,cells:[e.id,`<b>${e.n}</b>`,e.co,e.dep,bd(e.st)]}));
const NAV=[['dashboard','dash','Dashboard'],['employees','emp','Employees'],['vaccinations','vac','Vaccinations'],['examinations','exam','Medical Examinations'],['companies','co','Companies'],['reports','rep','Reports'],['appointments','cal','Calendar'],['notifications','bell','Notifications'],['settings','set','Settings']];
const logo=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${P.shield}</svg>`;
function loginView(){return`<div class="login"><div class="hero">${logo}<b>OMMS</b><span class="mu" style="font-size:18px">Occupational Medicine Management System</span><i class="mu" style="font:italic 18px Georgia,serif;margin-top:20px">Healthy Workers<br>Build a Safer Tomorrow</i></div><div class="lc card" style="padding:30px"><h1>Welcome back</h1><p class="mu">Sign in to your account</p><label>Email<input id="em" value="dr.salah@omms.dz" autocomplete="username"></label><label>Password<input id="pw" type="password" value="password" autocomplete="current-password"></label><label class="row" style="flex-direction:row;align-items:center"><input type="checkbox" checked style="accent-color:var(--teal)"> Remember me</label><button class="btn" style="justify-content:center" onclick="doLogin()">Sign in</button><div class="mu" style="text-align:center">or</div><button class="btn o" style="justify-content:center" onclick="doLogin()">Sign in with LDAP</button></div></div>`}
function render(focus){const r=document.body.dataset.page,id=new URLSearchParams(location.search).get('id');const root=document.getElementById('root');
 if(r=='login'){root.innerHTML=loginView();return}if(!S.user)return go('/login');
 
 document.title=(NAV.find(n=>n[0]==r)||[0,0,'OMMS'])[2]+' · OMMS';root.innerHTML=`<div class="app"><aside id="sd"><div class="logo">${logo}<div><b>OMMS</b><small>Occupational Medicine<br>Management System</small></div></div>${NAV.map(n=>`<a class="nav ${(r==n[0]||(r=='employee-details'&&n[0]=='employees'))?'on':''}" href="${n[0]}.html" onclick="document.getElementById('sd').classList.remove('open')">${ic(n[1])}${n[2]}</a>`).join('')}<a class="nav" href="login.html" onclick="sessionStorage.removeItem('omms_user');fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',keepalive:true}).catch(()=>{})">${ic('out')}Logout</a><div class="side-foot">Healthy Workers<br>Build a Safer Tomorrow</div></aside><div><header><button class="ib" id="mb" aria-label="Menu" onclick="document.getElementById('sd').classList.toggle('open')">${ic('menu')}</button><div class="search">${ic('search')}<input placeholder="Search by employee, company, or ID..." onkeydown="if(event.key=='Enter'){sessionStorage.setItem('omms_q',this.value);go('/employees')}" aria-label="Search"><span class="kbd">Ctrl K</span></div><button class="ib" aria-label="Notifications" onclick="go('/notifications')">${ic('bell')}<span class="dot">3</span></button><button class="ib" aria-label="Toggle theme" onclick="const h=document.documentElement;h.dataset.theme=h.dataset.theme=='light'?'dark':'light'">${ic('sun')}</button><div class="user"><div class="av">SB</div><div class="uname"><b>Dr. Salah Benali</b><div class="mu" style="font-size:12px">Occupational Doctor</div></div></div></header><main>${VIEW(id)}</main></div></div>`;
 if(focus){const i=document.getElementById(focus);i.focus();i.setSelectionRange(99,99)}}
addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key=='k'){e.preventDefault();const i=document.querySelector('.search input');if(i)i.focus()}});addEventListener('DOMContentLoaded',()=>render());
