/* dashboard page */
OMMS.mount(function dash(){const kp=[['emp','Total Employees','1,248','↑ 12%','vs. last month','blue','up'],['vac','Vaccinations Today','86','↑ 18%','vs. last week','teal','up'],['exam','Medical Examinations','52','↑ 9%','vs. last week','vio','up'],['warn','At Risk Employees','14','↓ 21%','vs. last month','red','dn']];
return`<div class="card" style="margin-bottom:16px;background:linear-gradient(120deg,rgba(30,70,150,.45),var(--card))"><div class="row sp"><div><div class="mu" style="font-size:11px;letter-spacing:.12em">WELCOME BACK</div><h1>Good morning, Dr. Salah 👋</h1><p class="mu">Here's what's happening with your occupational health center today.</p><p class="mu" style="margin-top:10px">${new Date().toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div><div style="font:italic 20px Georgia,serif;color:var(--mu)">“Prevention today,<br>health tomorrow.”</div></div></div>
<div class="grid g4">${kp.map(k=>`<div class="card kpi"><div class="ico" style="background:color-mix(in srgb,var(--${k[5]=='teal'?'teal':k[5]}) 22%,transparent);color:var(--${k[5]})">${ic(k[0])}</div><span>${k[1]}</span><b>${k[2]}</b><span class="${k[6]}">${k[3]} <span class="mu">${k[4]}</span></span></div>`).join('')}</div>
<div class="grid g2" style="margin-top:16px"><div class="grid"><div class="card"><div class="row sp"><div><h2>Vaccination Statistics</h2><span class="mu">Monthly vaccination numbers</span></div><span class="mu"><span style="color:var(--blue)">●</span> 2025 &nbsp;<span style="color:var(--teal)">●</span> 2026</span></div>${line([12,28,40,32,35,52,48,70,62,66,60,55],[25,48,80,64,70,100,90,150,120,128,110,100])}</div>
<div class="card"><div class="row sp"><h2>Recent Employees</h2><a href="employees.html" style="color:var(--blue)">View all →</a></div>${tbl(['ID','Name','Company','Department','Status'],empRows(DB.emps.slice(0,5)),r=>'/employee/'+r.id)}</div></div>
<div class="grid"><div class="card"><h2>Quick Actions</h2><div style="margin-top:10px">${[['Add New Employee','addEmp','emp'],['Record Vaccination','addVac','vac'],['Schedule Examination','addExam','exam'],['Manage Companies','go(\'/companies\')','co']].map(a=>`<button class="btn o" style="width:100%;justify-content:flex-start;margin-top:8px" onclick="${a[1].includes('(')?a[1]:a[1]+'()'}">${ic(a[2])}${a[0]}</button>`).join('')}</div></div>
<div class="card"><h2>Recent Activities</h2>${DB.acts.map(a=>`<div class="li"><div class="ico ${a[1]}">${ic(a[0])}</div><div><b>${a[2]}</b><div class="mu">${a[3]}</div></div><span class="mu" style="font-size:12px">${a[4]}</span></div>`).join('')}</div>
<div class="card"><h2>Monthly Summary</h2><div class="row" style="margin-top:10px">${donut(92)}<div style="flex:1;min-width:120px">${[['Vaccinated',86,'teal'],['Examined',52,'blue'],['Pending',8,'amber'],['At Risk',14,'red']].map(s=>`<div class="row sp"><span><span style="color:var(--${s[2]})">●</span> ${s[0]}</span><b>${s[1]}</b></div>`).join('')}</div></div></div></div></div>`});
