create extension if not exists pgcrypto;
create table companies (id uuid primary key default gen_random_uuid(), name text unique not null, industry text, address text, phone text, email text, contact_person text, active boolean default true, created_at timestamptz default now());
create table users (id uuid primary key default gen_random_uuid(), full_name text not null, email text unique not null, password_hash text not null, role text not null check (role in ('SUPER_ADMIN','OCCUPATIONAL_DOCTOR','NURSE','ADMINISTRATOR','COMPANY_MANAGER','VIEWER')), company_id uuid references companies, active boolean default true, last_login_at timestamptz, created_at timestamptz default now());
create table employees (id uuid primary key default gen_random_uuid(), employee_no text unique not null, first_name text not null, last_name text not null, date_of_birth date not null, gender text check (gender in ('M','F')), phone text, email text, company_id uuid not null references companies, department text, position text, hired_on date, status text not null default 'ACTIVE' check (status in ('ACTIVE','INACTIVE','ARCHIVED')), notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create index on employees (company_id); create index on employees (last_name, first_name);
create table vaccination_types (id uuid primary key default gen_random_uuid(), name text unique not null);
-- protocols are configured by doctors; no medical defaults are seeded
create table vaccination_protocols (id uuid primary key default gen_random_uuid(), vaccination_type_id uuid not null references vaccination_types, doses_required int not null check (doses_required > 0), interval_days int[] not null default '{}');
-- one row = a vaccine REQUIREMENT for an employee; NOT_STARTED means zero doses (no fake record)
create table vaccinations (id uuid primary key default gen_random_uuid(), employee_id uuid not null references employees, vaccination_type_id uuid not null references vaccination_types, protocol_id uuid references vaccination_protocols, status text not null default 'NOT_STARTED' check (status in ('NOT_STARTED','SCHEDULED','COMPLETED','OVERDUE','CANCELLED','UNKNOWN')), next_due_on date, notes text, unique (employee_id, vaccination_type_id));
create table vaccination_doses (id uuid primary key default gen_random_uuid(), vaccination_id uuid not null references vaccinations on delete cascade, dose_number int not null, administered_on date not null, batch_number text, manufacturer text, administered_by uuid references users, unique (vaccination_id, dose_number));
create table examinations (id uuid primary key default gen_random_uuid(), employee_id uuid not null references employees, exam_type text not null, exam_date date, doctor_id uuid references users, status text not null default 'SCHEDULED' check (status in ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','FOLLOW_UP_REQUIRED')), result text, follow_up_on date, notes text, created_at timestamptz default now());
create table appointments (id uuid primary key default gen_random_uuid(), employee_id uuid not null references employees, kind text not null check (kind in ('VACCINATION','EXAMINATION','FOLLOW_UP','OTHER')), starts_at timestamptz not null, status text not null default 'SCHEDULED' check (status in ('SCHEDULED','COMPLETED','CANCELLED','NO_SHOW')), assigned_to uuid references users, notes text, created_at timestamptz default now());
create index on appointments (starts_at, status);
create table notifications (id uuid primary key default gen_random_uuid(), user_id uuid references users, category text not null, title text not null, body text, employee_id uuid references employees, appointment_id uuid references appointments, read_at timestamptz, created_at timestamptz default now());
create table notification_jobs (id uuid primary key default gen_random_uuid(), appointment_id uuid not null references appointments on delete cascade, offset_days int not null, channel text not null default 'INTERNAL', run_at timestamptz not null, status text not null default 'PENDING' check (status in ('PENDING','PROCESSING','SENT','FAILED','CANCELLED')), attempts int not null default 0, unique (appointment_id, offset_days, channel));
create table notification_deliveries (id uuid primary key default gen_random_uuid(), job_id uuid not null references notification_jobs, attempted_at timestamptz default now(), status text not null, simulated boolean not null default false, error text);
create table audit_logs (id uuid primary key default gen_random_uuid(), user_id uuid, action text not null, resource text not null, resource_id text, result text not null default 'SUCCESS', ip text, user_agent text, created_at timestamptz default now());
create table system_settings (key text primary key, value jsonb not null, updated_at timestamptz default now());
insert into vaccination_types(name) values ('Hepatitis B'),('Influenza'),('Tetanus'),('COVID-19');
-- TEMPORARY admin: change the password immediately after first login
insert into users(full_name,email,password_hash,role) values ('Administrator','admin@omms.local',crypt('ChangeMe!123',gen_salt('bf',12)),'SUPER_ADMIN');
